config/routes.rb
AirBnb::Application.routes.draw do
  

  


  resources :bookings

  resources :users do
    resources :properties do
      resources :bookings
    end
    resources :bookings
  end





  resources :session,only: [ :create, :destroy]



root 'pages#home'
match '/help' , to: 'pages#help',via: 'get'
match '/about' ,to: 'pages#about',via: 'get'
match '/signup' , to: 'users#new' , via: 'get'
match '/signin' , to: 'session#new' , via: 'get'
match '/signout', to: 'session#destroy' , via: 'delete'
match '/search' , to: 'properties#search' , via: 'post'




  # The priority is base


 
  # See how all your routes lay out with "rake routes".

  # You can have the root of your site routed with "root"
  # root 'welcome#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end
  
  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/booking.rb
class Booking < ActiveRecord::Base
    belongs_to :property,foreign_key: "property_id" 
    belongs_to :user,foreign_key: "user_id" 
    
    validates :check_in_date,presence: true
    validates :check_out_date,presence: true
   

    scope  :booked_property, lambda{ |check_in_date,check_out_date | {:conditions => ["check_in_date between  ? AND  ? ",check_in_date,check_out_date]}}
    scope :history_by_property, lambda{|property_id| {:conditions => ["property_id =? ",property_id]}}
   
  
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:show, :edit, :update, :destroy]
  before_action :set_property_id, only: [:new, :edit, :update, :destroy]
  before_action :check_dates, only: [:create,:edit,:update]

  
  def index
    if (!params[:property_id].blank?)
      @bookings = current_user.properties.find_by(params[:property_id]).bookings
    else
      @bookings = current_user.booking.all
      p @bookings
    end
  end

  
  def show
  end

  
  def new
     @booking=Booking.new

  end

 
  def edit
   @bookings =@property.bookings.find_by('id=?',params[:id])
  end

  
  def create
    @booking = Booking.new(booking_params)
    @property_histories=Booking.where("property_id=? and check_in_date=? and check_out_date=?",params[:property_id],@booking.check_in_date,@booking.check_out_date)
    if (@property_histories.blank?)
    #respond_to do |format|
      if @booking.save
        redirect_to user_bookings_path(current_user.id)
        #format.html { redirect_to 'index', notice: 'Booking was successfully created.' }
        #format.json { render action: 'index', status: :created, location: @booking }
      else
        flash[:error]="Problem while booking try again later"
     
         redirect_to root_path
      #  format.html { render action: 'new' }
       # format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    else
        
         flash[:error]="Property not avail on this dates"
        redirect_to root_path

    end
  end

  
  def update
    respond_to do |format|
      if @booking.update(booking_params)
        format.html { redirect_to @booking, notice: 'Booking was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  
  def destroy
    @booking.destroy
    respond_to do |format|
      format.html { redirect_to bookings_url }
      format.json { head :no_content }
    end
  end

  private
    
    def set_property_id
      if(cookies[:property_id].blank?)
        cookies.permanent[:property_id]=params[:property_id]
      end
      @property=Property.find_by("id=?",cookies[:property_id])
    end

    def check_dates
     
     
    end

    def set_booking
      @booking = Property.find_by(params[:property_id]).bookings
    end

   
    def booking_params
      params.require(:booking).permit(:property_id, :user_id, :check_in_date, :check_out_date, :no_accomodates)
    end
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/views/bookings/_form.html.erb
<%= form_for(@booking, :url=> user_property_booking_path(params[:user_id],params[:property_id],params[:id])) do |f| %>
  <% if @booking.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@booking.errors.count, "error") %> prohibited this booking from being saved:</h2>

      <ul>
      <% @booking.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    
    <%= f.hidden_field :property_id,:value => params[:property_id] %>
  </div>
  <div class="field">
   
    <%= f.hidden_field :user_id ,:value => current_user.id%>
  </div>
  <div class="field">
    <%= f.label :check_in_date %><br>
    <input type="date" id="check_in_date"  name="booking[check_in_date]" value= <%= cookies[:check_in_date]%> >
  </div>
  <div class="field">
    <%= f.label :check_out_date %><br>
    <input type="date" id="check_out_date"  name="booking[check_out_date]" value= <%= cookies[:check_out_date]%> >
  </div>
  <div class="field">
    Maximum Number of Accomadates to allowed<br>
    <%= f.text_field :no_accomodates ,:readonly=> true,:value=>@property.accomodates %>
      <input type="hidden" value=<%= @property.price_night %> id="price_per">
  </div>
   Price per day
  <div>
    <%= @property.price_night %> 
  </div>
  <div class="actions">
    <%= f.submit :value=>"Book",:onclick =>" return calculate_search()" %>
  </div>
<% end %>

app/views/bookings/edit.html.erb
<h1>Editing booking</h1>

<%= render 'form' %>

<%= link_to 'Show', @booking ,:class => "btn btn-info"%> |
<%= link_to 'Back', bookings_path ,:class => "btn btn-info"%>

app/views/bookings/index.html.erb
<h1>Listing bookings</h1>
 <% unless @bookings.blank? %>
<table>
  <thead>
    <tr>
      <th>Property</th>
      <th>User</th>
      <th>Check in date</th>
      <th>Check out date</th>
      <th>No accomodates</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
   
    <% @bookings.each do |booking| %>
      <tr>
        <td><%= booking.property_id %></td>
        <td><%= booking.user.first_name %></td>
        <td><%= booking.check_in_date.to_date %></td>
        <td><%= booking.check_out_date.to_date %></td>
        <td><%= booking.no_accomodates %></td>
       
     <!--   <td><%= link_to 'Edit', edit_user_property_booking_path(current_user.id,params[:property_id],booking.id),:class => "btn btn-info" %></td> -->
        <td><%= link_to 'Destroy', booking, method: :delete, data: { confirm: 'Are you sure?' },:class => "btn btn-info" %></td>
      </tr>
    <% end %>
   
  </tbody>
</table>
 <%else%>

      <div class="alert alert-warning">There are no booking history </div>
    <%end%>
<br>

<%= link_to 'New Booking', new_booking_path,:class => "btn btn-info" %>

app/views/bookings/new.html.erb
<center>
<h1>New booking</h1>

<%= render 'form' %>
</center>

app/views/bookings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Property:</strong>
  <%= @booking.property_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @booking.user_id %>
</p>

<p>
  <strong>Check in date:</strong>
  <%= @booking.check_in_date %>
</p>

<p>
  <strong>Check out date:</strong>
  <%= @booking.check_out_date %>
</p>

<p>
  <strong>No accomodates:</strong>
  <%= @booking.no_accomodates %>
</p>

<%= link_to 'Edit', edit_booking_path(@booking) %> |
<%= link_to 'Back', bookings_path %>