config/routes.rb
AirBnb::Application.routes.draw do
  

  


  resources :bookings

  resources :users do
    resources :properties do
      resources :bookings
    end
    resources :bookings
  end





  resources :session,only: [ :create, :destroy]



root 'pages#home'
match '/help' , to: 'pages#help',via: 'get'
match '/about' ,to: 'pages#about',via: 'get'
match '/signup' , to: 'users#new' , via: 'get'
match '/signin' , to: 'session#new' , via: 'get'
match '/signout', to: 'session#destroy' , via: 'delete'
match '/search' , to: 'properties#search' , via: 'post'




  # The priority is base


 
  # See how all your routes lay out with "rake routes".

  # You can have the root of your site routed with "root"
  # root 'welcome#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end
  
  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/property.rb
class Property < ActiveRecord::Base
    belongs_to :user,foreign_key: "user_id" 
    has_many :bookings,dependent: :destroy
    validates :accomodates,presence: true
    validates :city,presence: true
    validates :address,presence: true
    validates :price_night,presence: true
    validates :title,presence: true
    scope :search_city , lambda{ |city,user|  {:conditions => ["city = ? and user_id !=?",city,user] }  }

end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  before_action :set_property, only: [:show, :edit, :update, :destroy]

  
  def index
    @properties = current_user.properties
  end

  
  def show

  end

 def search
  cookies.delete(:check_in_date)
  cookies.delete(:check_out_date)
    if params[:city].blank?
      flash[:error]="Invalid place"
      redirect_to 'root_path'
    else 
      if current_user
        if params[:check_in_date].blank? or params[:check_out_date].blank?
          @properties = Property.search_city(params[:city],current_user.id)
        else 
          @scope_prop = Property.search_city(params[:city],current_user.id)
          @property_histories=Booking.booked_property(params[:check_in_date],params[:check_out_date])

          if  !( @property_histories.select(:property_id).map(&:property_id).blank?) 
            @properties= @scope_prop.where("id != ?", @property_histories.select(:property_id).map(&:property_id).first)
          else
            @properties=@scope_prop
          end
          cookies.permanent[:check_in_date]=params[:check_in_date]
          cookies.permanent[:check_out_date]=params[:check_out_date]
        end
      else
        @properties = Property.where("city=?",params[:city])
      end
   
    end 
  end

  
  def new
    @property = Property.new
  end

  
  def edit
  end

  
  def create
    @property = Property.new(property_params)

    respond_to do |format|
      if @property.save
        format.html { redirect_to user_properties_path(current_user.id), notice: 'Property was successfully created.' }
        format.json { render action: 'show', status: :created, location: @property }
      else
        format.html { render action: 'new' }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  
  def update
    respond_to do |format|
      if @property.update(property_params)
        format.html { redirect_to user_properties_path(current_user.id), notice: 'Property was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  
  def destroy
    @property.destroy
    respond_to do |format|
      format.html { redirect_to properties_url }
      format.json { head :no_content }
    end
  end

  private
    
    def set_property
      @property = Property.find(params[:id])
    end

    
    def property_params
      params.require(:property).permit(:user_id, :home_type, :room_type, :accomodates, :city, :address, :price_night, :title)
    end
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/views/properties/_form.html.erb
<%= form_for(@property, :url=> user_properties_path(current_user.id)) do |f| %>
  <% if @property.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@property.errors.count, "error") %> prohibited this property from being saved:</h2>

      <ul>
      <% @property.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    
    <%= f.hidden_field :user_id, :value=> current_user.id %>
  </div>
  <div class="field">
    <%= f.label :home_type %><br>
   <%= f.select :home_type, options_for_select([['House', 'House'], ['Villa', 'Villa'] , ['Apartment', 'Apartment'] ]) %>
  </div>
  <div class="field">
    <%= f.label :room_type %><br>
   <%= f.select :room_type, options_for_select([['Entier Home', 'Entier Home'], ['Private Room', 'Private Room'] , ['Shared', 'Shared'] ]) %>
  </div>
  <div class="field">
    <%= f.label :accomodates %><br>
    <%= f.number_field :accomodates %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city, :onfocus=>"new google.maps.places.Autocomplete(this);" %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :price_night %><br>
    <%= f.number_field :price_night %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/properties/edit.html.erb
<h1>Editing property</h1>

<%= render 'form' %>


<%= link_to 'Back', user_properties_path,:class => "btn btn-info" %>

app/views/properties/index.html.erb
<h1>Listing properties</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Home type</th>
      <th>Room type</th>
      <th>Accomodates</th>
      <th>City</th>
      <th>Address</th>
      <th>Price night</th>
      <th>Title</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @properties.each do |property| %>
      <tr>
        <td><%= current_user.first_name %></td>
        <td><%= property.home_type %></td>
        <td><%= property.room_type %></td>
        <td><%= property.accomodates %></td>
        <td><%= property.city %></td>
        <td><%= property.address %></td>
        <td><%= property.price_night %></td>
        <td><%= property.title %></td>
        <td><%= link_to 'Booking History', user_property_bookings_path(current_user.id,property.id),:class => "btn btn-info" %></td>
        <td><%= link_to 'Edit', edit_user_property_path(current_user.id,property.id) ,:class => "btn btn-info"%></td>
        <td><%= link_to 'Destroy', user_property_path(current_user.id,property.id),:class => "btn btn-info", method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Property', new_user_property_path ,:class => "btn btn-info"%>

app/views/properties/new.html.erb
<center>
<h1>Listing your property</h1>

<%= render 'form' %>
</center>

app/views/properties/search.html.erb
<center>
	
<div id="flash">
       <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
     
  </div>



	<%unless !@property.blank?  %>
		<% unless   @properties.blank? %>
			
			<% @properties  %>
					
			<div class="div_table">
				<div class="div_table_header">
					<div class="div_th"> Owner </div> 
					<div class="div_th">Home Type  </div> 
					<div class="div_th">Number of Accommodates Allowed  </div>
					<div class="div_th">Address </div> 
					<div class="div_th">Price Per Night </div>
		 			<div class="div_th"> </div>
				</div>

				<% @properties.each do |p| %>



 				<div class="div_tr">
	 				<div class="div_td"> 
					
					</div>
					<div class="div_td">
						<%= p.home_type  %>
				 	</div>
					<div class="div_td">
						<%= p.accomodates  %> 
					</div>
					<div class="div_td">
						<%=p.address%>
					</div>
	 				<div class="div_td">
	 					<%=p.price_night%>Rs.
	 				</div>
					<div>
					<%=link_to "Book" ,new_user_property_booking_path(current_user.id,p.id),:class => "btn btn-info" %>
					</div>
				</div>

				<%end%>
			</div>



		<% else%>
			<div class="jumbotron">
			  <div class="container">
				<div class="alert alert-danger">No Properties avail at this time try again with alternate</div>
				
				</div></div>
		<% end %>
	<% end %>

	</div>
	






</center>


 

app/views/properties/show.html.erb
<p id="notice"><%= notice %></p>



<p>
  <strong>Home type:</strong>
  <%= @property.home_type %>
</p>

<p>
  <strong>Room type:</strong>
  <%= @property.room_type %>
</p>

<p>
  <strong>Accomodates:</strong>
  <%= @property.accomodates %>
</p>

<p>
  <strong>City:</strong>
  <%= @property.city %>
</p>

<p>
  <strong>Address:</strong>
  <%= @property.address %>
</p>

<p>
  <strong>Price night:</strong>
  <%= @property.price_night %>
</p>

<p>
  <strong>Title:</strong>
  <%= @property.title %>
</p>

<%= link_to 'Edit', edit_user_property_path(current_user.id,@property.id),:class => "btn btn-info" %> |
<%= link_to 'Back', user_properties_path ,:class => "btn btn-info"%>