config/routes.rb
AirBnb::Application.routes.draw do
  

  


  resources :bookings

  resources :users do
    resources :properties do
      resources :bookings
    end
    resources :bookings
  end





  resources :session,only: [ :create, :destroy]



root 'pages#home'
match '/help' , to: 'pages#help',via: 'get'
match '/about' ,to: 'pages#about',via: 'get'
match '/signup' , to: 'users#new' , via: 'get'
match '/signin' , to: 'session#new' , via: 'get'
match '/signout', to: 'session#destroy' , via: 'delete'
match '/search' , to: 'properties#search' , via: 'post'




  # The priority is base


 
  # See how all your routes lay out with "rake routes".

  # You can have the root of your site routed with "root"
  # root 'welcome#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end
  
  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AirBnb</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false&libraries=places"></script>
</head>
<body>




<div class="innersearch1">
  <span class="innersearch">
    
      <%= form_tag(search_path) do %>
            <table class="search-query ">
              <tr><td><img class="img_icon"/></td>
                <td >
                  <input type="text" name="city"   class="search-query input-medium search_text_color" placeholder="Where you are going??"  onfocus="new google.maps.places.Autocomplete(this);"/>
                  check In 
                  <input type="date" name="check_in_date" id="check_in_date"  placeholder="Check in "  width="50px" style="margin-top:5px"  >
                   Check Out
                  <input type="date" name="check_out_date" id="check_out_date"  placeholder="Check out " style="margin-top:5px" >
                  
                  <button class="btn btn-info"  onclick="return calculate_search()" >Search</button>
                  </td>
              </tr>
          </table>
      
            <% end %>
  </span>
  <span class="menu_width">
         <ul class="nav nav-pills pull-right ">
           <li ><%= link_to "Home",    root_path ,:class => "btn btn-info"%></li>
           <li><%= link_to "Help",    help_path,:class => "btn btn-info" %></li>
           <li><%= link_to "About", about_path ,:class => "btn btn-info"%></li>
            <% if signed_in? %>
              <li id="fat-menu" class="dropdown btn btn-info">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" >
                  Account <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Profile", current_user %></li>
                  <li><%= link_to "Settings", edit_user_path(:id => current_user.id ) %></li>
                  <li><%= link_to "My Bookings", user_bookings_path(current_user.id ) %></li>
                  <li><%= link_to "My Properties", user_properties_path(current_user.id ) %></li>
                  <li class="divider"></li>
                  <li>
                    <%= link_to "Sign out", signout_path, method: "delete" %>
                  </li>
                </ul>
              </li>
              <li >
              
                <%= link_to "  List Your Space ", new_user_property_path(current_user.id), :class => "btn btn-info"   %> 
              </li>
            <% else %>
              <li><%= link_to "Sign in", signin_path ,:class => "btn btn-info"%></li>
              <li><%= link_to "Sign Up", signup_path ,:class => "btn btn-info"%></li>
            <% end %>
          </ul>
      </span>
</div>
<center>

 <div id="flash">
       <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
    </div>
<%= yield %>
</center>
<!-- Footer -->
<div  ><center>
  <span class="span_safty">
    <div class="safty">
      <img src="/assets/trust_img.jpg" class="img-circle" width="150px" height="150px">
    </div>
    <div class="safty_txt">
      World-class security & communications features mean you never have to accept a booking unless you're 100% comfortable.
    </div>

  </span>
  <span class="span_safty">
    <div class="safty">
      <img src="/assets/secure_img.png"  width="150px" height="150px"></div>
    <div class="safty_txt">
      
Your peace of mind is priceless. So we don't charge for it. Every single booking on Airbnb is covered by our Host Guarantee - at no cost to you.</div>

  </span>
  <span class="span_safty">
      <div class="safty">
      <img src="/assets/icon_guaranteed_2.png" class="img-circle" width="150px" height="150px"></div>
    <div class="safty_txt">Secure Payments
Our fast, flexible payment system puts money in your bank account 24 hours after guests check in.</div>

  </span>
</div>
</body>
</html>